version: "3.9"

services:
  db:
    image: postgres:16
    container_name: odoo19-prod-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:19.0
    container_name: odoo19-prod-app
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      HOST: ${ODOO_DB_HOST:-db}
      USER: ${ODOO_DB_USER:-${POSTGRES_USER}}
      PASSWORD: ${ODOO_DB_PASSWORD:-${POSTGRES_PASSWORD}}
      DB_NAME: ${ODOO_DB_NAME:-${POSTGRES_DB}}
    volumes:
      - ./addons:/mnt/extra-addons:ro
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - filestore:/var/lib/odoo
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge

volumes:
  postgres-data:
  filestore:
