services:
  db:
    image: postgres:16
    container_name: odoo19-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:19.0
    container_name: odoo19-app
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - filestore:/var/lib/odoo
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge

volumes:
  postgres-data:
  filestore:
